openapi: 3.0.2
info:
  title: "Learn Deposit App"
  description: "Deposit REST API"
  version: "1.0"
paths:
  /auth/authToken:
    get:
      tags:
        - authorization
      description: "Get auth token using credentials"
      parameters:
        - in: query
          name: "login"
          description: "The username of a user"
          required: true
          schema:
            type: string

        - in: query
          name: "password"
          description: "The password of a user"
          required: true
          schema:
            type: string
            format: password
      responses:
        200:
          description: "Successful auth"
          content:
            application/json:
              schema:
                description: "Auth token"
                type: string
        400:
          description: "Bad request"

        403:
          description: "Something's went wrong"
          content:
            text/plain:
              schema:
                type: string

  /deposit/operations/new:
    post:
      tags:
        - deposits
      description: "Create a new deposit"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createDepositSchema'

      responses:
        201:
          description: "New deposit was created"
          content:
            application/json:
              schema:
                description: "GUID of a new deposit"
                type: string

        400:
          description: "Bad request"

        403:
          description: "Something's went wrong"
          content:
            text/plain:
              schema:
                type: string

  /deposit/operations/add:
    put:
      tags:
        - deposits
      description: "Add some money to deposit"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addDepositSchema'
      responses:
        200:
          description: "The deposit was replenished"

        400:
          description: "Bad request"

        403:
          description: "Something's went wrong"
          content:
            text/plain:
              schema:
                type: string

  /deposit/operations/withdraw:
    put:
      tags:
        - deposits
      description: "Withdraw some money from deposit"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/withdrawDepositSchema'

      responses:
        200:
          description: "The deposit was replenished"

        400:
          description: "Bad request"

        403:
          description: "Something's went wrong"
          content:
            text/plain:
              schema:
                type: string

  /deposit/operations/close:
    put:
      tags:
        - deposits
      description: "Close deposit"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/closeDepositSchema'
      responses:
        200:
          description: "The deposit was closed"

        400:
          description: "Bad request"

        403:
          description: "Something's went wrong"
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    createDepositSchema:
      type: object
      required:
        - authToken
        - amount
      properties:
        authToken:
          type: string
          description: "Auth token"
        amount:
          type: integer
          format: int32
          description: "Amount of money which you wish to make a deposit"

    addDepositSchema:
      type: object
      required:
        - authToken
        - depositGuid
        - amount
      properties:
        authToken:
          type: string
          description: "Auth token"
        depositGuid:
          type: string
          description: "GUID of a deposit"
        amount:
          type: integer
          format: int32
          description: "Amount of money which you wish to add to deposit"

    withdrawDepositSchema:
      type: object
      required:
        - authToken
        - depositGuid
        - amount
      properties:
        authToken:
          type: string
          description: "Auth token"
        depositGuid:
          type: string
          description: "GUID of a deposit"
        amount:
          type: integer
          format: int32
          description: "Amount of money which you wish to withdraw from deposit"

    closeDepositSchema:
      type: object
      required:
        - authToken
        - depositGuid
      properties:
        authToken:
          type: string
          description: "Auth token"
        depositGuid:
          type: string
          description: "GUID of a deposit"











